server:
  port: 8011
  servlet:
   encoding:
    charset: UTF-8
    force: true
    enabled: true
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: final
    password: final
mybatis:
  type-aliases-package: com.ducks.demys.boot.vo
